import { StyleSheet } from 'react-native';

export const spotlightProps = {
  dimOpacity: 0.68,
  borderRadius: 22,
  borderWidth: 1.5,
  padding: 8,
  borderColor: '#8FB7FF',
  allowOverlayClick: true,
} as const;

export const styles = StyleSheet.create({
  screen: { flex: 1, position: 'relative', backgroundColor: '#101624' },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 64,
    paddingBottom: 28,
  },
  header: { gap: 10, marginBottom: 20 },
  eyebrow: {
    color: '#8FB7FF',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  title: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  subtitle: { color: '#B8C2D8', fontSize: 16, lineHeight: 23 },
  scenarioList: { gap: 12 },
  navCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    borderRadius: 22,
    backgroundColor: '#1B2440',
    borderWidth: 1,
    borderColor: '#2B3658',
  },
  navIcon: { fontSize: 28 },
  navCopyWrap: { flex: 1, gap: 4 },
  navTitle: { color: '#FFFFFF', fontSize: 17, fontWeight: '800' },
  navCopy: { color: '#B8C2D8', fontSize: 14, lineHeight: 19 },
  navArrow: { color: '#8FB7FF', fontSize: 24, fontWeight: '800' },
  scenarioHeader: { gap: 8, marginBottom: 16 },
  scenarioTitle: { color: '#FFFFFF', fontSize: 26, fontWeight: '800' },
  scenarioCopy: { color: '#B8C2D8', fontSize: 15, lineHeight: 21 },
  flexGap: { gap: 12 },
  lifecycleStage: {
    flex: 1,
    gap: 12,
  },
  fullscreenSpotlight: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 50,
    elevation: 50,
  },
  card: {
    gap: 8,
    padding: 22,
    borderRadius: 24,
    backgroundColor: '#F5F8FF',
  },
  cardLabel: {
    color: '#4263EB',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  cardTitle: { color: '#111827', fontSize: 23, fontWeight: '800' },
  cardCopy: { color: '#475569', fontSize: 15, lineHeight: 22 },
  row: { flexDirection: 'row', gap: 14 },
  feature: {
    flex: 1,
    minHeight: 146,
    gap: 8,
    padding: 18,
    borderRadius: 22,
    backgroundColor: '#1B2440',
    borderWidth: 1,
    borderColor: '#2B3658',
  },
  featureIcon: { fontSize: 28 },
  featureTitle: { color: '#FFFFFF', fontSize: 17, fontWeight: '800' },
  featureCopy: { color: '#B8C2D8', fontSize: 14, lineHeight: 20 },
  actions: { gap: 10, marginTop: 'auto' },
  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: '#8FB7FF',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#3B4768',
  },
  ghostButton: { backgroundColor: '#1B2440' },
  pressedButton: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  buttonText: { color: '#0B1020', fontSize: 15, fontWeight: '800' },
  secondaryButtonText: { color: '#F5F8FF' },
  ghostButtonText: { color: '#F5F8FF' },
  tooltip: {
    gap: 8,
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
  },
  tooltipStep: { color: '#4263EB', fontSize: 12, fontWeight: '800' },
  tooltipTitle: { color: '#111827', fontSize: 18, fontWeight: '800' },
  tooltipCopy: { color: '#475569', fontSize: 14, lineHeight: 20 },
  tooltipActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  counterRow: { gap: 10, marginTop: 4 },
  counterButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: '#A7F3D0',
  },
  counterText: { color: '#DDE7FF', fontSize: 15, fontWeight: '700' },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    padding: 24,
  },
  emptyIcon: { fontSize: 52 },
  emptyTitle: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyCopy: {
    color: '#B8C2D8',
    fontSize: 16,
    lineHeight: 23,
    textAlign: 'center',
  },
  offscreen: { position: 'absolute', top: -9999 },
  portalAnchor: { width: 1, height: 1 },
  portalHost: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  windowOverlayHost: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  layeringSpotlight: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 10,
    elevation: 10,
  },
  layeringTooltipWrap: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 120,
    zIndex: 100,
    elevation: 100,
  },
  layeringTooltipArrow: {
    position: 'absolute',
    top: -6,
    left: 44,
    width: 14,
    height: 14,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
    transform: [{ rotate: '45deg' }],
    zIndex: 101,
    elevation: 101,
  },
  layeringTooltipCard: {
    gap: 8,
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#8FB7FF',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.22,
    shadowRadius: 24,
    zIndex: 100,
    elevation: 100,
  },
});
